import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

// Regression guard for T69: the author of a governance/voting record
// (budget_proposals, ideas, petitions) must not retain the blanket "owner
// manage" (for all) grant once other residents have acted on it. The
// 20260522000016 migration replaces that grant with operation-scoped owner
// policies that let the author update/delete their row only while NO
// vote/signature child row exists; comitet keeps full moderation via the
// standard "comitet write" policy and members keep read via "members read".
// This test reads the migration SQL (backend-free, runs offline in CI) and
// asserts the narrowing is in place and applied to exactly the governance
// tables, so the bug class cannot silently return.

const migrationsDir = join(process.cwd(), 'supabase', 'migrations');

function readMigration(name: string): string {
  return readFileSync(join(migrationsDir, name), 'utf8').toLowerCase();
}

function allMigrationSql(): string {
  return readdirSync(migrationsDir)
    .filter((f) => f.endsWith('.sql'))
    .sort()
    .map((f) => readFileSync(join(migrationsDir, f), 'utf8'))
    .join('\n')
    .toLowerCase();
}

// The governance tables whose owner grant must be narrowed, with their
// vote/signature child table and the parent foreign-key column on it.
const governanceTables = [
  { table: 'budget_proposals', child: 'budget_votes', fk: 'proposal_id' },
  { table: 'ideas', child: 'idea_votes', fk: 'idea_id' },
  { table: 'petitions', child: 'petition_signatures', fk: 'petition_id' },
] as const;

describe('governance owner grants are least-privilege (T69)', () => {
  const migration = readMigration('20260522000016_governance_owner_least_privilege.sql');
  const allSql = allMigrationSql();

  it('drops the blanket "owner manage" grant before re-scoping', () => {
    expect(migration).toContain('drop policy if exists "owner manage" on %s');
  });

  it('grants the author only insert / unlocked-update / unlocked-delete (never for all)', () => {
    expect(migration).toContain('create policy "owner insert" on %s for insert');
    expect(migration).toContain('create policy "owner update unlocked" on %1$s for update');
    expect(migration).toContain('create policy "owner delete unlocked" on %1$s for delete');
    // The helper must not re-introduce a for-all owner grant.
    expect(migration).not.toMatch(/create policy "owner[^"]*" on %\d?\$?s for all/);
  });

  it('locks owner update and delete behind the absence of any vote/signature', () => {
    // Both the update and the delete policy must carry the not-exists lock that
    // resolves the child vote/signature table.
    const lock = /not exists \(select 1 from %3\$i where %4\$i = %1\$s\.id\)/g;
    expect([...migration.matchAll(lock)]).toHaveLength(2);
  });

  it('keeps the actor a member of the row asociatie on every owner operation', () => {
    // insert with check, update using + with check, delete using.
    const memberChecks = [...migration.matchAll(/= auth\.uid\(\) and is_member\(asociatie_id\)/g)];
    expect(memberChecks.length).toBeGreaterThanOrEqual(4);
  });

  it('applies the narrowed grant to exactly the governance tables, each with its child + fk', () => {
    for (const { table, child, fk } of governanceTables) {
      const call = new RegExp(
        `apply_governance_owner_rls\\('${table}',\\s*'author_user_id',\\s*'${child}',\\s*'${fk}'\\)`,
      );
      expect(call.test(migration)).toBe(true);
    }
    const calls = [...migration.matchAll(/apply_governance_owner_rls\('([a-z_]+)'/g)].map((m) => m[1]);
    const distinct = [...new Set(calls)].filter((t) => t.length > 0);
    expect(distinct.sort()).toEqual(governanceTables.map((g) => g.table).sort());
  });

  it('only narrows the standard policies, leaving comitet moderation intact', () => {
    // The standard "comitet write" (for all) and "members read" policies are
    // generated by apply_standard_rls and must not be touched here, so comitet
    // can still moderate and members can still read a locked governance row.
    expect(migration).not.toContain('drop policy if exists "comitet write"');
    expect(migration).not.toContain('drop policy if exists "members read"');
    for (const { table } of governanceTables) {
      expect(allSql).toContain(`apply_standard_rls('${table}')`);
    }
  });
});
