import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

// Regression guard for T45: every owner-scoped policy must also require the
// actor to be an active member of the row's asociatie_id, not merely the row's
// owner. The "owner manage" policy generated by apply_owner_rls once gated only
// on owner_col = auth.uid(), so on a table carrying a direct asociatie_id a user
// could own/insert a row stamped with another asociație's id. This test reads
// the migration SQL (backend-free, runs offline in CI) and asserts the
// tightened generator requires is_member(asociatie_id) in both USING and
// WITH CHECK, that the policy is re-applied to every owner-scoped table, and
// that the member-insert helper keeps its is_member requirement.

const migrationsDir = join(process.cwd(), 'supabase', 'migrations');

function readMigration(name: string): string {
  return readFileSync(join(migrationsDir, name), 'utf8').toLowerCase();
}

function allMigrationSql(): string {
  return readdirSync(migrationsDir)
    .filter((f) => f.endsWith('.sql'))
    .sort()
    .map((f) => readFileSync(join(migrationsDir, f), 'utf8'))
    .join('\n')
    .toLowerCase();
}

// The owner-scoped tables and their owner columns, mirroring the
// apply_owner_rls calls across the migration suite.
const ownerScopedTables = [
  'discussion_messages',
  'resident_posts',
  'budget_proposals',
  'ideas',
  'petitions',
  'lending_items',
  'resident_directory_consent',
  'pets',
  'bookings',
  'bikes',
  'marketplace_listings',
  'carpool_profiles',
  'birthdays_consent',
  'kids_age_ranges',
  'access_codes',
  'sitter_profiles',
  'skill_offerings',
  'group_buys',
  'group_buy_signups',
  'pledges',
  'anonymous_messages',
  'contractor_recommendations',
  'duty_volunteers',
  'task_signups',
  'wiki_suggested_edits',
] as const;

describe('owner-scoped RLS requires active membership (T45)', () => {
  const migration = readMigration('20260522000013_owner_rls_membership.sql');
  const allSql = allMigrationSql();

  it('redefines apply_owner_rls to require is_member(asociatie_id) in both clauses', () => {
    // The generator body must add the membership check to both the USING and
    // the WITH CHECK expressions so neither read nor write escapes the tenant.
    const generator = new RegExp(
      'create or replace function apply_owner_rls\\(tbl regclass, owner_col text\\)' +
        '[\\s\\S]*?using \\(%i = auth\\.uid\\(\\) and is_member\\(asociatie_id\\)\\)' +
        '[\\s\\S]*?with check \\(%i = auth\\.uid\\(\\) and is_member\\(asociatie_id\\)\\)',
    );
    expect(generator.test(migration)).toBe(true);
  });

  it('re-applies the tightened owner policy to every owner-scoped table', () => {
    for (const table of ownerScopedTables) {
      expect(migration).toContain(`select reapply_owner_rls('${table}',`);
    }
  });

  it('drops the existing owner policy before recreating it (idempotent re-apply)', () => {
    expect(migration).toContain('drop policy if exists "owner manage" on %s');
  });

  it('reapply_owner_rls routes through the tightened generator', () => {
    // It must call apply_owner_rls (not re-declare a loose policy inline), so the
    // membership requirement can never drift between the two.
    const reapply = new RegExp(
      'create or replace function reapply_owner_rls\\(tbl regclass, owner_col text\\)' +
        '[\\s\\S]*?perform apply_owner_rls\\(tbl, owner_col\\)',
    );
    expect(reapply.test(migration)).toBe(true);
  });

  it('covers exactly the owner-scoped tables that apply_owner_rls is called on', () => {
    // Catalogue every apply_owner_rls('table', ...) call across the suite and
    // assert each is re-applied here, so a future owner-scoped table cannot be
    // added without also being tenant-membership tightened.
    const calls = [...allSql.matchAll(/apply_owner_rls\('([a-z_]+)'/g)].map((m) => m[1]);
    const distinct = [...new Set(calls)].filter((t) => t.length > 0);
    for (const table of distinct) {
      expect(ownerScopedTables).toContain(table as (typeof ownerScopedTables)[number]);
    }
    expect([...ownerScopedTables].sort()).toEqual(distinct.sort());
  });

  it('member-insert helper still requires is_member(asociatie_id)', () => {
    // T45 is the owner-policy companion; the member-insert policy was already
    // tenant-scoped and must stay that way.
    const memberInsert = new RegExp(
      'create policy "member insert own" on %s for insert' +
        '[\\s\\S]*?with check \\(is_member\\(asociatie_id\\) and %i = auth\\.uid\\(\\)\\)',
    );
    expect(memberInsert.test(allSql)).toBe(true);
  });
});
